# Site settings
title: The Way of Life
subtitle:
email: aadityamaheshwari@gmail.com
description: A static blog built using Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 350 La Salle Road
city: Goleta
state: CA
zip_code: 93117
country: United States of America
phone: (805) 455-0382

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/aadityamaheshwari
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/aadityamaheshwari
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
